# Generated by Django 3.2.4 on 2021-09-14 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='created_data',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='updated_data',
            new_name='updated_date',
        ),
    ]
